version: "3.9"
services:
  app:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    volumes:
      - .:/home/app
